#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

         1: 1
          3: 1,3
           6: 1,2,3,6
           10: 1,2,5,10
           15: 1,3,5,15
           21: 1,3,7,21
           28: 1,2,4,7,14,28
           We can see that 28 is the first triangle number to have over five divisors.

           What is the value of the first triangle number to have over five hundred divisors?

           Some Math:
                T(N)    =   T(N-1) + N  { T(0) = 0
                =============================

                T(1)    =   T(0)   + 1  = 1
                T(2)    =   T(1)   + 2  = 1 + 2 = 3
                T(3)    =   T(2)   + 3  = 3 + 3 = 6

'''

import time
import sys
import math

def noOfDivisors(n):
    sqRtN = int(math.sqrt(n))
    count = 0
    for i in range(1,sqRtN):
        if n%i == 0:
            if n/i == i:
                count += 1
            else:
                count += 2
    return count


def triangleNoWithMoreThan500Divisors():
    t1 = 1
    tn  = t1
    i = 2
    while ( noOfDivisors(tn) < 500 ) :
        tn = t1 + i
        t1 = tn
        i = i + 1
    return tn

start_time = time.time()
print triangleNoWithMoreThan500Divisors()

print("--- %s seconds ---" % (time.time() - start_time))
