#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pent        agonal  Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal   Hn=n(2n−1           )   1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 =    40755.

Find the next triangle number that is also pentagonal and hexagonal.

'''

import time
import sys
import math


def getHexagonalNo(n):
    return n * ( 2 * n - 1 )

def getPentagonalNo(n):
    return n * ( 3 * n - 1 ) / 2

def getTriangleNo(n):
        return n * ( n + 1 ) / 2

def Solve_Naive():
    TnDict = {}
    PnDict = {}
    HnDict = {}

    res = 0
    i = 0
    n = 1
    while i < 3:
        Tn = getTriangleNo(n)
        Pn = getPentagonalNo(n)
        PnDict[Pn] = 1
        Hn = getHexagonalNo(n)
        HnDict[Hn] = 1
        if Tn in PnDict:
            if Tn in HnDict:
                res = Tn
                i += 1
        n += 1

    return res

def Solve():
    return Solve_Naive()

start_time = time.time()
print Solve()
print("--- %s seconds ---" % (time.time() - start_time))

