#!/bin/bash

which python
if test $? -ne 0; then
    printf "Don't see python here \n"
    printf "Install Python and comeback ..\n"
    exit;
fi

for file in $(ls problem*.py | sort -n -t - -k 2);
do
    echo ""
    filename=$(basename ${file%.*})
    echo "Executing  $filename"
    if test -f $filename.in; then
        `which python` $file  < $filename.in
    else
        `which python` $file  
    fi

    echo ""
done

for file in $(ls problem*.cpp | sort -n -t - -k 2);
do
     echo ""
    filename=$(basename ${file%.*})
    echo "Executing  $filename"
    #echo "c++  $file -o $filename -std=c++11"
    c++  $file -o $filename -std=c++11
    ./$filename
    echo ""

done
