#!/bin/bash

for file in $(ls problem*.py | sort -n -t - -k 2);
do
    echo ""
    filename=$(basename ${file%.*})
    echo "Executing  $filename"
    if test -f $filename.in; then
        `which python` $file  < $filename.in
    else
        `which python` $file  
    fi

    echo ""
done
