#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
import time

def evenFibSum(n):
    f1  = 0
    f2  = 2
    sum = 2
    f   = 4*f2 + f1
    while ( f < n ):
        sum += f
        f1 = f2
        f2 = f
        f  = 4*f2 + f1

    return sum


start_time = time.time()
print evenFibSum(4000000)
print("--- %s seconds ---" % (time.time() - start_time))

